# Generated by Django 5.0.2 on 2024-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='static/assets/media/avatars/avatar', upload_to='static/assets/media/avatars', verbose_name='Profile Picture'),
        ),
    ]
