# Generated by Django 5.0.2 on 2024-04-14 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibo',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_module.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.TextField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('Level 9', 'Level 9'), ('Level 10', 'Level 10')], primary_key=True, serialize=False, verbose_name='Level'),
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
