# Generated by Django 5.0.2 on 2024-04-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIBORates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arp_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Fiat per ARP')),
                ('monthly_subscription', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monthly Subscription Amount')),
                ('yearly_subscription', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Yearly Subscription Amount')),
                ('charge_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Percentage Charge per Transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIBOWallet',
            fields=[
                ('wallet_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inflow', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outflow', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_id', models.CharField(max_length=10)),
                ('bank_code', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=15)),
                ('account_name', models.CharField(max_length=150)),
                ('account_type', models.CharField(max_length=100, null=True)),
                ('payout', models.IntegerField(null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Withdraw', 'Withdraw'), ('Purchase', 'Purchase')], max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('ref', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='YearlyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
