# Generated by Django 5.0.2 on 2024-03-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('asset', models.CharField(max_length=50, verbose_name='Asset')),
                ('description', models.TextField(verbose_name='Description')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Daily Rate')),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimum_duration', models.IntegerField(verbose_name='Duration before Sales(days)')),
                ('maximum_duration', models.IntegerField(verbose_name='Duration before Expiration(days)')),
                ('total_shares', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Available Shares')),
                ('sold_out_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('percentage_bought', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('share_rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Fiat per Asset Shares')),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(verbose_name='Availability for Purchase')),
            ],
            options={
                'ordering': ('sector',),
            },
        ),
        migrations.CreateModel(
            name='AssetSales',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Enter Amount')),
                ('share_value', models.FloatField()),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-transaction_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sector', models.CharField(max_length=50, verbose_name='Sector')),
                ('description', models.TextField(verbose_name='Description')),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(verbose_name='Availability for Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPurchases',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Enter Amount')),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('expiring_datetime', models.DateTimeField(auto_now_add=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ledger_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiboearn.asset')),
            ],
            options={
                'ordering': ('-transaction_datetime',),
            },
        ),
    ]
