# Generated by Django 5.0.2 on 2024-03-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_and_staff_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
